apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.pvName }}
spec:
  storageClassName: {{ .Values.pv.storageClassName | quote }}
  capacity:
    storage: {{ .Values.pv.capacity }}
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.pv.hostPath }}
    type: Directory
