apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.pvcName }}
spec:
  storageClassName: {{ .Values.pv.storageClassName | quote }}
  volumeName: {{ .Values.pv.pvName }}
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.pv.capacity }}
