# In some cases, such as for Cluster Bootstrap, it is desirable to connect to the pods directly,
#   bypassing any liveness/readiness checks or load balancing. For such situations we provide
#   a discovery implementation that uses the Kubernetes API

# If your Kubernetes cluster has Role-Based Access Control (RBAC) enabled, you’ll also have to grant
#   the Service Account that your pods run under access to list pods.
# The following configuration can be used as a starting point. It creates a Role, pod-reader,
#   which grants access to query pod information. It then binds the default Service Account
#   to the Role by creating a RoleBinding. Adjust as necessary.
#
# https://doc.akka.io/docs/akka-management/current/discovery/kubernetes.html#role-based-access-control
#
# Since Role & RoleBinding are namespace-bound, it might be good enough to use the default
#   ServiceAccount in a namespace where Akka cluster is deployed

# Create a role, `pod-reader`, that can list pods and
# bind the default service account in the namespace
# that the binding is deployed to to that role.

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
  # Uses the default service account.
  # Consider creating a dedicated service account to run your
  # Akka Cluster services and binding the role to that one.
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
