apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.pvcName }}
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
