apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.pvName }}
spec:
  storageClassName: {{ .Values.pv.storageClassName | quote }}
  capacity:
    storage: 60Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: {{ .Values.pv.nfsServer }}
    path: {{ .Values.pv.datasetPath }}
